# Generated by Django 3.1.2 on 2020-10-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emojis', '0001_initial'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emoji',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='emojis.emoji'),
        ),
    ]
